### DEVO Config File for EDS ###

# VO config (increase for better accuracy)
PATCHES_PER_FRAME: 96
REMOVAL_WINDOW: 22
OPTIMIZATION_WINDOW: 10
PATCH_LIFETIME: 13

# threshold for keyframe removal
KEYFRAME_THRESH: 25.0

# camera motion model
MOTION_MODEL: 'DAMPED_LINEAR'
MOTION_DAMPING: 0.5

# maybe use mixed precision for inference
MIXED_PRECISION: True

# Select between random, gradient, scorer
PATCH_SELECTOR: 'scorer'
# Normalizer (only evs): none, rescale, standard (std)
NORM: 'std'
# Eval mode of patch selector (random, topk, multinomial)
SCORER_EVAL_MODE: 'multi'
SCORER_EVAL_USE_GRID: True
